
MAX_ARTICLES = 3

HEADER = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

HEADER = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0'}


MARKETWATCH_SKIP_CONTENT = 'This story was auto-generated by Automated Insights'
MARKETWATCH_URL = f"https://www.marketwatch.com/investing/stock/@STOCKCODE?mod=search_symbol"

SEEKINGALPHA_SKIP_CONTENT = 'Getty Images'
SEEKINGALPHA_URL = f"https://seekingalpha.com"